name: 'Sonar Results Action'
description: 'For use with pull request checks'

runs:
  using: "composite"
  steps:
    - run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - run: |
        ${{ github.action_path }}/action.py
      shell: bash
